CREATE SEQUENCE IF NOT EXISTS arts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardarts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardkeywords_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cards_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardtags_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardtypes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS colours_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS keywords_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tags_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE artcosts
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    colour_id INTEGER,
    amount    INTEGER,
    art_id    INTEGER,
    CONSTRAINT artcosts_pk PRIMARY KEY (id)
);

CREATE TABLE arts
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           TEXT,
    effect         TEXT,
    damage         INTEGER,
    crit_colour_id INTEGER,
    CONSTRAINT pk_arts PRIMARY KEY (id)
);

CREATE TABLE cardarts
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid INTEGER                                  NOT NULL,
    artid  INTEGER                                  NOT NULL,
    CONSTRAINT pk_cardarts PRIMARY KEY (id)
);

CREATE TABLE cardkeywords
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid    INTEGER                                  NOT NULL,
    keywordid INTEGER                                  NOT NULL,
    CONSTRAINT pk_cardkeywords PRIMARY KEY (id)
);

CREATE TABLE cards
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid         TEXT                                     NOT NULL,
    cardset        TEXT                                     NOT NULL,
    cardtype       INTEGER                                  NOT NULL,
    card_colour_id INTEGER                                  NOT NULL,
    batonpass      TEXT                                     NOT NULL,
    holomem        TEXT                                     NOT NULL,
    bloomlvl       TEXT                                     NOT NULL,
    hp             INTEGER                                  NOT NULL,
    rarity         TEXT                                     NOT NULL,
    image          TEXT,
    extra_id       INTEGER,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

CREATE TABLE cardtags
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid INTEGER                                  NOT NULL,
    tagid  INTEGER                                  NOT NULL,
    CONSTRAINT pk_cardtags PRIMARY KEY (id)
);

CREATE TABLE cardtypes
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                     NOT NULL,
    CONSTRAINT pk_cardtypes PRIMARY KEY (id)
);

CREATE TABLE colours
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    colour    TEXT,
    image_url TEXT,
    CONSTRAINT pk_colours PRIMARY KEY (id)
);

CREATE TABLE extra
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    effect TEXT,
    CONSTRAINT pk_extra PRIMARY KEY (id)
);

CREATE TABLE keywords
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type   TEXT                                     NOT NULL,
    name   TEXT                                     NOT NULL,
    effect TEXT                                     NOT NULL,
    CONSTRAINT pk_keywords PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                     NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

ALTER TABLE artcosts
    ADD CONSTRAINT artcosts_arts_id_fk FOREIGN KEY (art_id) REFERENCES arts (id) ON DELETE NO ACTION;

ALTER TABLE artcosts
    ADD CONSTRAINT artcosts_colours_id_fk FOREIGN KEY (colour_id) REFERENCES colours (id) ON DELETE NO ACTION;

ALTER TABLE arts
    ADD CONSTRAINT arts_colours_id_fk FOREIGN KEY (crit_colour_id) REFERENCES colours (id) ON DELETE NO ACTION;

ALTER TABLE cards
    ADD CONSTRAINT cards_cardtypes_id_fk FOREIGN KEY (cardtype) REFERENCES cardtypes (id) ON DELETE RESTRICT;

ALTER TABLE cards
    ADD CONSTRAINT cards_colours_id_fk FOREIGN KEY (card_colour_id) REFERENCES colours (id) ON DELETE NO ACTION;

ALTER TABLE cards
    ADD CONSTRAINT cards_extra_id_fk FOREIGN KEY (extra_id) REFERENCES extra (id) ON DELETE NO ACTION;

ALTER TABLE cardarts
    ADD CONSTRAINT fk_cardarts_on_artid FOREIGN KEY (artid) REFERENCES arts (id) ON DELETE RESTRICT;

ALTER TABLE cardarts
    ADD CONSTRAINT fk_cardarts_on_cardid FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardkeywords
    ADD CONSTRAINT fk_cardkeywords_on_cardid FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardkeywords
    ADD CONSTRAINT fk_cardkeywords_on_keywordid FOREIGN KEY (keywordid) REFERENCES keywords (id) ON DELETE RESTRICT;

ALTER TABLE cardtags
    ADD CONSTRAINT fk_cardtags_on_cardid FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardtags
    ADD CONSTRAINT fk_cardtags_on_tagid FOREIGN KEY (tagid) REFERENCES tags (id) ON DELETE NO ACTION;