-- Fix tables whose id columns were created without identity/defaults.
-- Without this, Hibernate inserts NULL into the primary key.

-- EXTRA
ALTER TABLE IF EXISTS extra
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ARTCOSTS
ALTER TABLE IF EXISTS artcosts
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
