CREATE TABLE collection_cards
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    collection_id INTEGER                                  NOT NULL,
    card_id       INTEGER                                  NOT NULL,
    card_count    INTEGER,
    CONSTRAINT pk_collectioncards PRIMARY KEY (id)
);

CREATE TABLE collections
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   INTEGER,
    visibility INTEGER,
    CONSTRAINT pk_collections PRIMARY KEY (id)
);

CREATE TABLE deck_cards
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deck_id    INTEGER                                  NOT NULL,
    card_id    INTEGER                                  NOT NULL,
    card_count INTEGER                                  NOT NULL,
    CONSTRAINT pk_deckcards PRIMARY KEY (id)
);

CREATE TABLE decks
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id       INTEGER                                  NOT NULL,
    deck_name        VARCHAR(255)                             NOT NULL,
    deck_description VARCHAR(255),
    visibility       INTEGER                                  NOT NULL,
    CONSTRAINT pk_decks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                             NOT NULL,
    email         VARCHAR(255)                             NOT NULL,
    password_hash VARCHAR(255)                             NOT NULL,
    bio           VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE collection_cards
    ADD CONSTRAINT FK_COLLECTIONCARDS_ON_CARDID FOREIGN KEY (card_id) REFERENCES cards (id);

ALTER TABLE collection_cards
    ADD CONSTRAINT FK_COLLECTIONCARDS_ON_COLLECTIONID FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE CASCADE;

ALTER TABLE deck_cards
    ADD CONSTRAINT FK_DECKCARDS_ON_CARDID FOREIGN KEY (card_id) REFERENCES cards (id);

ALTER TABLE deck_cards
    ADD CONSTRAINT FK_DECKCARDS_ON_DECKID FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE;

DROP SEQUENCE public.arts_id_seq CASCADE;

DROP SEQUENCE public.cardarts_id_seq CASCADE;

DROP SEQUENCE public.cardkeywords_id_seq CASCADE;

DROP SEQUENCE public.cards_id_seq CASCADE;

DROP SEQUENCE public.cardtags_id_seq CASCADE;

DROP SEQUENCE public.cardtypes_id_seq CASCADE;

DROP SEQUENCE public.colours_id_seq1 CASCADE;

DROP SEQUENCE public.keywords_id_seq CASCADE;

DROP SEQUENCE public.tags_id_seq CASCADE;

ALTER TABLE cardtypes
    ALTER COLUMN name SET DEFAULT null;