CREATE SEQUENCE IF NOT EXISTS arts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardarts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardkeywords_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cards_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardtags_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cardtypes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS keywords_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tags_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE arts
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name CHAR,
    CONSTRAINT arts_pk PRIMARY KEY (id)
);

CREATE TABLE cardarts
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid INTEGER                                  NOT NULL,
    artid  INTEGER                                  NOT NULL,
    CONSTRAINT cardarts_pk PRIMARY KEY (id)
);

CREATE TABLE cardkeywords
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid    INTEGER                                  NOT NULL,
    keywordid INTEGER                                  NOT NULL,
    CONSTRAINT cardkeywords_pk PRIMARY KEY (id)
);

CREATE TABLE cards
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid     INTEGER                                  NOT NULL,
    cardset    CHAR                                     NOT NULL,
    cardtype   CHAR                                     NOT NULL,
    cardcolour CHAR                                     NOT NULL,
    batonpass  CHAR                                     NOT NULL,
    holomem    CHAR                                     NOT NULL,
    bloomlvl   CHAR                                     NOT NULL,
    hp         INTEGER                                  NOT NULL,
    isbuzz     BOOLEAN                                  NOT NULL,
    rarity     CHAR                                     NOT NULL,
    CONSTRAINT cards_pk PRIMARY KEY (id)
);

CREATE TABLE cardtags
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid INTEGER                                  NOT NULL,
    tagid  INTEGER                                  NOT NULL,
    CONSTRAINT cardtags_pk PRIMARY KEY (id)
);

CREATE TABLE cardtypes
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name CHAR                                     NOT NULL,
    CONSTRAINT cardtypes_pk PRIMARY KEY (id)
);

CREATE TABLE keywords
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type   CHAR                                     NOT NULL,
    name   CHAR                                     NOT NULL,
    effect CHAR                                     NOT NULL,
    CONSTRAINT keywords_pk PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name CHAR                                     NOT NULL,
    CONSTRAINT tags_pk PRIMARY KEY (id)
);

ALTER TABLE cardtypes
    ADD CONSTRAINT cardtypes_pk_2 UNIQUE (name);

ALTER TABLE tags
    ADD CONSTRAINT tags_pk_2 UNIQUE (name);

ALTER TABLE cardarts
    ADD CONSTRAINT cardarts_arts_id_fk FOREIGN KEY (artid) REFERENCES arts (id) ON DELETE RESTRICT;

ALTER TABLE cardarts
    ADD CONSTRAINT cardarts_cards_id_fk FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardkeywords
    ADD CONSTRAINT cardkeywords_cards_id_fk FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardkeywords
    ADD CONSTRAINT cardkeywords_keywords_id_fk FOREIGN KEY (keywordid) REFERENCES keywords (id) ON DELETE RESTRICT;

ALTER TABLE cards
    ADD CONSTRAINT cards_cardtypes_name_fk FOREIGN KEY (cardtype) REFERENCES cardtypes (name) ON DELETE RESTRICT;

ALTER TABLE cardtags
    ADD CONSTRAINT cardtags_cards_id_fk FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardtags
    ADD CONSTRAINT cardtags_tags_id_fk FOREIGN KEY (tagid) REFERENCES tags (id) ON DELETE NO ACTION;