CREATE TABLE public.colours
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    colour    TEXT,
    image_url TEXT,
    CONSTRAINT pk_colours PRIMARY KEY (id)
);

CREATE TABLE public.extra
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    effect TEXT,
    CONSTRAINT pk_extra PRIMARY KEY (id)
);

CREATE TABLE artcosts
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    colour_id INTEGER,
    amount    INTEGER,
    art_id    INTEGER,
    CONSTRAINT pk_artcosts PRIMARY KEY (id)
);

CREATE TABLE arts
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           TEXT,
    effect         TEXT,
    damage         INTEGER,
    crit_colour_id INTEGER,
    CONSTRAINT pk_arts PRIMARY KEY (id)
);

CREATE TABLE cardarts
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid INTEGER                                  NOT NULL,
    artid  INTEGER                                  NOT NULL,
    CONSTRAINT pk_cardarts PRIMARY KEY (id)
);

CREATE TABLE cardkeywords
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid    INTEGER                                  NOT NULL,
    keywordid INTEGER                                  NOT NULL,
    CONSTRAINT pk_cardkeywords PRIMARY KEY (id)
);

CREATE TABLE cards
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid         VARCHAR(255)                             NOT NULL,
    cardset        TEXT                                     NOT NULL,
    cardtype       INTEGER                                  NOT NULL,
    card_colour_id INTEGER                                  NOT NULL,
    batonpass      TEXT                                     NOT NULL,
    holomem        TEXT                                     NOT NULL,
    bloomlvl       TEXT                                     NOT NULL,
    hp             INTEGER                                  NOT NULL,
    rarity         TEXT                                     NOT NULL,
    image          TEXT,
    extra_id       INTEGER,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

CREATE TABLE cardtags
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cardid INTEGER                                  NOT NULL,
    tagid  INTEGER                                  NOT NULL,
    CONSTRAINT pk_cardtags PRIMARY KEY (id)
);

CREATE TABLE cardtypes
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                     NOT NULL,
    CONSTRAINT pk_cardtypes PRIMARY KEY (id)
);

CREATE TABLE collection_cards
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    collection_id INTEGER                                  NOT NULL,
    card_id       INTEGER                                  NOT NULL,
    card_count    INTEGER,
    CONSTRAINT pk_collectioncards PRIMARY KEY (id)
);

CREATE TABLE collections
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   INTEGER,
    visibility INTEGER,
    CONSTRAINT pk_collections PRIMARY KEY (id)
);

CREATE TABLE deck_cards
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deck_id    INTEGER                                  NOT NULL,
    card_id    INTEGER                                  NOT NULL,
    card_count INTEGER                                  NOT NULL,
    CONSTRAINT pk_deckcards PRIMARY KEY (id)
);

CREATE TABLE decks
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id       INTEGER                                  NOT NULL,
    deck_name        VARCHAR(255)                             NOT NULL,
    deck_description VARCHAR(255),
    visibility       INTEGER                                  NOT NULL,
    CONSTRAINT pk_decks PRIMARY KEY (id)
);

CREATE TABLE keywords
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type   TEXT                                     NOT NULL,
    name   TEXT                                     NOT NULL,
    effect TEXT                                     NOT NULL,
    CONSTRAINT pk_keywords PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                     NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                             NOT NULL,
    email         VARCHAR(255)                             NOT NULL,
    password_hash VARCHAR(255)                             NOT NULL,
    bio           VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE artcosts
    ADD CONSTRAINT FK_ARTCOSTS_ON_ART FOREIGN KEY (art_id) REFERENCES arts (id);

ALTER TABLE artcosts
    ADD CONSTRAINT FK_ARTCOSTS_ON_COLOUR FOREIGN KEY (colour_id) REFERENCES public.colours (id);

ALTER TABLE arts
    ADD CONSTRAINT FK_ARTS_ON_CRIT_COLOUR FOREIGN KEY (crit_colour_id) REFERENCES public.colours (id);

ALTER TABLE cardarts
    ADD CONSTRAINT FK_CARDARTS_ON_ARTID FOREIGN KEY (artid) REFERENCES arts (id) ON DELETE RESTRICT;

ALTER TABLE cardarts
    ADD CONSTRAINT FK_CARDARTS_ON_CARDID FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardkeywords
    ADD CONSTRAINT FK_CARDKEYWORDS_ON_CARDID FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardkeywords
    ADD CONSTRAINT FK_CARDKEYWORDS_ON_KEYWORDID FOREIGN KEY (keywordid) REFERENCES keywords (id) ON DELETE RESTRICT;

ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_CARDTYPE FOREIGN KEY (cardtype) REFERENCES cardtypes (id) ON DELETE RESTRICT;

ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_CARD_COLOUR FOREIGN KEY (card_colour_id) REFERENCES public.colours (id) ON DELETE RESTRICT;

ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_EXTRA FOREIGN KEY (extra_id) REFERENCES public.extra (id);

ALTER TABLE cardtags
    ADD CONSTRAINT FK_CARDTAGS_ON_CARDID FOREIGN KEY (cardid) REFERENCES cards (id) ON DELETE RESTRICT;

ALTER TABLE cardtags
    ADD CONSTRAINT FK_CARDTAGS_ON_TAGID FOREIGN KEY (tagid) REFERENCES tags (id);

ALTER TABLE collection_cards
    ADD CONSTRAINT FK_COLLECTIONCARDS_ON_CARDID FOREIGN KEY (card_id) REFERENCES cards (id);

ALTER TABLE collection_cards
    ADD CONSTRAINT FK_COLLECTIONCARDS_ON_COLLECTIONID FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE CASCADE;

ALTER TABLE deck_cards
    ADD CONSTRAINT FK_DECKCARDS_ON_CARDID FOREIGN KEY (card_id) REFERENCES cards (id);

ALTER TABLE deck_cards
    ADD CONSTRAINT FK_DECKCARDS_ON_DECKID FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE;