ALTER TABLE collections
    ADD CONSTRAINT FK_COLLECTIONS_ON_OWNERID FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE decks
    ADD CONSTRAINT FK_DECKS_ON_CREATORID FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE cardtypes
    ALTER COLUMN name SET DEFAULT null;

ALTER TABLE collections
    ALTER COLUMN owner_id SET NOT NULL;